version: 2
jobs:
    deploy:
        docker:
            - image: circleci/buildpack-deps:stretch
              environment:
                IMAGE_NAME: icecube/webgl-viewer
        steps:
            - checkout
            - setup_remote_docker
            - run: |
                echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
            - run: |
                docker build -t $IMAGE_NAME:$TAG .
            - run: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                docker push $IMAGE_NAME:$TAG
workflows:
    version: 2
    build:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        only: master
    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
